export enum FailureCode {
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  REVERSAL_WOULD_OVERDRAW = 'REVERSAL_WOULD_OVERDRAW',
  REFERENCE_NOT_FOUND = 'REFERENCE_NOT_FOUND',
  REFERENCE_ALREADY_REVERSED = 'REFERENCE_ALREADY_REVERSED',
  REFERENCE_KIND_NOT_REVERSIBLE = 'REFERENCE_KIND_NOT_REVERSIBLE',
  REFERENCE_AMOUNT_MISMATCH = 'REFERENCE_AMOUNT_MISMATCH',
  REFERENCE_CONTEXT_MISMATCH = 'REFERENCE_CONTEXT_MISMATCH',
  REFERENCE_NOT_PROCESSED = 'REFERENCE_NOT_PROCESSED',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  PLAYER_WALLET_MISMATCH = 'PLAYER_WALLET_MISMATCH',
  INTERNAL_KIND_NOT_ALLOWED = 'INTERNAL_KIND_NOT_ALLOWED',
}
